Develop
mate-academy/js_sort_table_DOM pull request #173
Opened 2021-03-11 13:29 UTC by Jastler

- [DEMO LINK](https://jastler.github.io/js_sort_table_DOM/)

2021-03-11 14:10 UTC, yashnyi approved these changes
good job!

2021-03-12 15:57 UTC, solaryasha requested changes

2021-03-12 15:57 UTC, solaryasha commented on src/scripts/main.js
> +function sorted(index) {
Що sorted ?

2021-03-12 15:57 UTC, solaryasha commented on src/scripts/main.js
> +      return firstRow > secondRow ? 1 : -1;
Використай localeCompare

2021-03-12 15:57 UTC, solaryasha commented on src/scripts/main.js
> +      const salaryA = parseFloat(firstRow.replace(/\$/g, ''));
Винеси конвертацію в окрему функцію

2021-03-12 15:57 UTC, solaryasha commented on src/scripts/main.js
> +      const salaryB = parseFloat(secondRow.replace(/\$/g, ''));
Ти можеш сортувати не тільки salary, назва непідходяща

2021-03-12 15:57 UTC, solaryasha commented on src/scripts/main.js
> +thead.addEventListener('click', e => {
```suggestion
thead.addEventListener('click', event => {
```

2021-03-12 15:57 UTC, solaryasha commented on src/scripts/main.js
> +  const thIndex = e.target.cellIndex;
header

2021-03-15 10:23 UTC, Vladimir-Beliy requested changes
используй switch case и имя колонок для определения метода сортировки

2021-03-15 10:23 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +    }
этого не должно быть в  сорте

2021-03-15 13:56 UTC, Vladimir-Beliy approved these changes

2021-03-15 13:56 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +    case 'Position':
tbody.append(...rows);

должен происходить тут после switch case а не внтури фнукций сорта

2026-05-12 17:03 UTC, closed without merging