solution
mate-academy/js_sort_table_DOM pull request #174
Opened 2021-03-11 14:08 UTC by yashnyi

[DEMO LINK](https://yashnyi.github.io/js_sort_table_DOM/)

2021-03-11 14:50 UTC, Jastler approved these changes
nice!

2021-03-12 16:10 UTC, solaryasha requested changes

2021-03-12 16:10 UTC, solaryasha commented on src/scripts/main.js
> +        .replace('$', '').replace(',', '');
Винеси цю конвертацію в окрему функцію

2021-03-12 16:10 UTC, solaryasha commented on src/scripts/main.js
> +    if (rowA.children[columnIndex].textContent.includes('$')) {
Ще в колонці age є числа, якщо вік буде більше 100 років, посортує неправильно

2021-03-15 10:27 UTC, Vladimir-Beliy requested changes

2021-03-15 10:27 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +    }
это не должно происходить в сорте
используй switch case

2021-03-15 13:55 UTC, Vladimir-Beliy approved these changes

2021-03-15 13:55 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +  switch (heading.textContent) {
body.append(...rows);
должен происходить тут после switch  case а не внутри сорта

2025-09-01 20:49 UTC, closed without merging