Develop
mate-academy/js_sort_table_DOM pull request #68
Opened 2020-10-18 15:59 UTC by AndriiManyak

[DEMO LINK](https://andriimanyak.github.io/js_sort_table_DOM/)

2020-10-18 19:53 UTC, goncharukop approved these changes

2020-10-20 09:58 UTC, aliceblunt8 requested changes

2020-10-20 09:58 UTC, aliceblunt8 commented on src/scripts/main.js
> +  }
abundant, you've put an event listener on the table head (it contains only th)

2020-10-20 09:58 UTC, aliceblunt8 commented on src/scripts/main.js
> +    let previousContent = previous.cells[indexOfCellToSort].textContent;
```suggestion
    let previousRow = previous.cells[indexOfCellToSort].textContent;
```

2020-10-20 09:58 UTC, aliceblunt8 commented on src/scripts/main.js
> +    let currentContent = current.cells[indexOfCellToSort].textContent;
```suggestion
    let currentRow = current.cells[indexOfCellToSort].textContent;
```

2020-10-20 09:58 UTC, aliceblunt8 commented on src/scripts/main.js
> +    return previousContent.localeCompare(currentContent);
this should be in default case

2020-10-20 09:58 UTC, aliceblunt8 commented on src/scripts/main.js
> +    return previousContent.localeCompare(currentContent);
it's cool that you use switch, but case 2 or case 3 aren't very informative for other developers (or even you a couple of weeks later)
let's switch and sort depending on the header name (salary, age, etc)

2020-10-20 12:54 UTC, aliceblunt8 approved these changes

2026-02-12 23:07 UTC, closed without merging