solution
mate-academy/js_sort_table_DOM pull request #964
Opened 2024-09-25 02:08 UTC by Grifion

[DEMO LINK](https://Grifion.github.io/js_sort_table_DOM/)

2024-09-25 05:54 UTC, lerastarynets requested changes
Pls try to pass all tests, if your tests pass locally, but you encounter a problem in server tests, pls attach a screen of all local tests passing

2024-09-27 19:47 UTC, Grifion commented
![Test ](https://github.com/user-attachments/assets/6fdb6085-ae4e-4189-87f8-57580e5b6575)

2024-09-27 20:04 UTC, etojeDenys requested changes
sorting in demo link doesn't work, try to fix it

2024-09-28 06:23 UTC, volodymyr-soltys97 approved these changes
Good job 👍

2026-05-17 21:43 UTC, closed without merging